### ISSUE TITLE
grafana的json模板

### ISSUE THREAD

**Issue by trotyoung** [zhangguanzhang/harbor_exporter#1]
能否慷慨提供下grafana dashboard json...微信公众号没有回复了😂

**Comment by zhangguanzhang** [comment]
那个公众号不是我发的，公众号的所有者把公众号卖了。我个人是没搞grafana的，直接Prometheus上用volume和last_scrape_err写个告警就够用了，每次我们线上harbor出问题都能告警到

**Comment by trotyoung** [comment]
> 那个公众号不是我发的，公众号的所有者把公众号卖了。我个人是没搞grafana的，直接Prometheus上用volume和last_scrape_err写个告警就够用了，每次我们线上harbor出问题都能告警到

好的，那我结合场景自己研究下~多谢！！
