### ISSUE TITLE
关于harbor-exporter 问题反馈

### ISSUE THREAD

**Issue by lrwh** [zhangguanzhang/harbor_exporter#2]
编码bug

**Steps to reproduce the issue:**

1.exporter.go 78行代码 用户名参数赋值会导致密码参数覆盖

问题截图
![image](https://user-images.githubusercontent.com/17264378/154030057-c8266949-f5ef-4da3-82d0-aaf05f9936f1.png)

**Comment by zhangguanzhang** [comment]
已经更新，和推送到 ` zhangguanzhang/harbor_exporter:v0.1.1 zhangguanzhang/harbor_exporter`
